#!/usr/bin/env node
// Regenerates public/sitemap.xml from the same route source of truth used by
// scripts/prerender.mjs (route-meta.json + solution/workshop slugs), so the
// sitemap can never drift out of sync with what's actually built and indexable.
// Priority/changefreq are preserved from the existing sitemap when a URL was
// already curated there; new URLs fall back to sane defaults.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const rootDir = path.resolve(import.meta.dirname, "..");
const SITE_URL = "https://www.cyrruscs.com";

const routeMeta = JSON.parse(
  await readFile(path.join(rootDir, "src/lib/route-meta.json"), "utf-8"),
);

const solutionsSrc = await readFile(path.join(rootDir, "src/lib/solutions-data.ts"), "utf-8");
const solutionSlugs = [...solutionsSrc.matchAll(/slug:\s*"([a-z0-9-]+)"/g)].map((m) => m[1]);

// Workshops still marked "próximamente" (comingSoon: true) are intentionally
// excluded — they're noindex'd in the app and shouldn't be submitted for crawl.
const workshopsSrc = await readFile(path.join(rootDir, "src/lib/workshops-data.ts"), "utf-8");
// Top-level array entries are exactly `  {` at line-start; split there rather
// than matching "slug:" (which also appears in the interface declaration).
const workshopBlocks = workshopsSrc.split(/\r?\n(?=  \{\r?\n)/);
const allWorkshopSlugs = [];
const liveWorkshopSlugs = [];
for (const block of workshopBlocks) {
  const slugMatch = block.match(/slug:\s*"([a-z0-9-]+)"/);
  if (!slugMatch) continue;
  allWorkshopSlugs.push(slugMatch[1]);
  if (/comingSoon:\s*true/.test(block)) continue;
  liveWorkshopSlugs.push(slugMatch[1]);
}
const comingSoonWorkshopSlugs = new Set(allWorkshopSlugs.filter((s) => !liveWorkshopSlugs.includes(s)));

const extraRoutes = ["/privacidad", "/cookies"];

const esRoutes = [
  ...new Set([
    ...Object.keys(routeMeta),
    ...solutionSlugs.map((slug) => `/metodo-cira/seleccion-de-soluciones/${slug}`),
    ...extraRoutes,
  ]),
].filter((p) => {
  const workshopSlug = p.match(/^\/leadership-academy\/([a-z0-9-]+)$/)?.[1];
  return !workshopSlug || !comingSoonWorkshopSlugs.has(workshopSlug);
});

// Preserve hand-tuned priority/changefreq from the existing sitemap so
// regenerating doesn't flatten deliberate curation; default for anything new.
const existingXml = await readFile(path.join(rootDir, "public/sitemap.xml"), "utf-8").catch(() => "");
const existing = new Map();
for (const match of existingXml.matchAll(
  /<loc>([^<]+)<\/loc>\s*<lastmod>[^<]*<\/lastmod>\s*<changefreq>([^<]+)<\/changefreq>\s*<priority>([^<]+)<\/priority>/g,
)) {
  existing.set(match[1], { changefreq: match[2], priority: match[3] });
}

const today = new Date().toISOString().slice(0, 10);

function entryFor(loc, fallbackPriority, fallbackChangefreq) {
  const prior = existing.get(loc);
  return {
    loc,
    changefreq: prior?.changefreq ?? fallbackChangefreq,
    priority: prior?.priority ?? fallbackPriority,
  };
}

function urlBlock({ loc, esLoc, enLoc, changefreq, priority }) {
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
    <xhtml:link rel="alternate" hreflang="es" href="${esLoc}" />
    <xhtml:link rel="alternate" hreflang="en" href="${enLoc}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${esLoc}" />
  </url>`;
}

const blocks = [];
for (const esPath of esRoutes) {
  const enPath = esPath === "/" ? "/en" : `/en${esPath}`;
  const esLoc = `${SITE_URL}${esPath === "/" ? "/" : esPath}`;
  const enLoc = `${SITE_URL}${enPath}`;
  const depth = esPath === "/" ? 0 : esPath.split("/").filter(Boolean).length;
  const esDefaultPriority = esPath === "/" ? "1.0" : Math.max(0.3, 0.9 - depth * 0.15).toFixed(1);
  const enDefaultPriority = esPath === "/" ? "0.9" : Math.max(0.1, Number(esDefaultPriority) - 0.1).toFixed(1);
  const defaultChangefreq = esPath === "/" ? "weekly" : "monthly";

  const esEntry = entryFor(esLoc, esDefaultPriority, defaultChangefreq);
  const enEntry = entryFor(enLoc, enDefaultPriority, defaultChangefreq);

  blocks.push(urlBlock({ loc: esLoc, esLoc, enLoc, ...esEntry }));
  blocks.push(urlBlock({ loc: enLoc, esLoc, enLoc, ...enEntry }));
}

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Auto-generated by scripts/generate-sitemap.mjs from src/lib/route-meta.json +
  solutions-data.ts + workshops-data.ts (excluding "próximamente" workshops).
  Do not hand-edit URLs/structure here — edit route-meta.json or the data
  files instead and re-run \`node scripts/generate-sitemap.mjs\`.
  Priority/changefreq for existing URLs are preserved across regenerations.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${blocks.join("\n")}
</urlset>
`;

await writeFile(path.join(rootDir, "public/sitemap.xml"), xml, "utf-8");
console.log(`generate-sitemap: wrote ${blocks.length} URLs to public/sitemap.xml`);
